"""add attendance and raw_punches tables

Revision ID: daed54e802e1
Revises: fd6ff52ad66c
Create Date: 2026-03-06 10:31:43.582878

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daed54e802e1'
down_revision: Union[str, None] = 'fd6ff52ad66c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###