"""add date column to attendance

Revision ID: fd6ff52ad66c
Revises: 8511ae4a612d
Create Date: 2026-03-06 10:24:00.887986

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd6ff52ad66c'
down_revision: Union[str, None] = '8511ae4a612d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance')
    op.drop_table('raw_punches')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_punches',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('punch_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('punch_type', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='raw_punches_pkey')
    )
    op.create_table('attendance',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('check_in', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('check_out', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name='attendance_member_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='attendance_pkey')
    )
    # ### end Alembic commands ###